#!/bin/bash
#set -x
set -e

export READLINE_DIR=~/homebrew/Cellar/readline/8.1.1
shopt -s extglob
mkdir -p objs_san
mkdir -p objs_leaks
cd objs_san
gcc -Wall -Wextra -c -g -fsanitize=address  -I.. ../../!(minishe*).c -I $READLINE_DIR/include/
cd ..
cd objs_leaks
gcc -Wall -Wextra -c -g -I.. ../../!(minishe*).c -I $READLINE_DIR/include/
cd ..

make -C ..
for file in test*.c
do
	export BASE=${file%.*}
	echo "checking $BASE"
	gcc -Wall -Wextra -g -fsanitize=address -L../Libft -I.. $file objs_san/*.o -o ${file%.*} -lft -I $READLINE_DIR/include/ -L $READLINE_DIR/lib/ -lreadline ../get_next_line/get_next_line.a
	./${file%.*} > ${file%.*}.check
	diff ${file%.*}.check ${file%.*}.out
	sed -i '' '$ d' $file 
	echo "system(\"leaks -quiet $BASE > leaks_output\");}" >> $file 
	gcc -Wall -Wextra -g -L../Libft -I.. $file objs_leaks/*.o -o ${file%.*} -lft -I $READLINE_DIR/include/ -L $READLINE_DIR/lib/ -lreadline ../get_next_line/get_next_line.a
	sed -i '' '$ d' $file
	echo "}" >> $file 
	./${file%.*} > ${file%.*}.check
	diff ${file%.*}.check ${file%.*}.out
	cat leaks_output | grep -q ' 0 leaks' || { echo "leaks found!"; exit 1; }
done
shopt -u extglob

./integration_tests

echo FINISHED!!!!!
