#!/bin/bash
#set -x
set -e

shopt -s extglob
mkdir -p objs_san
mkdir -p objs_leaks

cd objs_leaks
gcc -Wall -Wextra -c -g -I.. ../../!(minishe*).c -I $READLINE_DIR/include/
cd ..

make -C ..
for file in test_replace_parts.c test_shell_split.c test_wildcard.c
do
	export BASE=${file%.*}
	echo "checking $BASE"
	gcc -Wall -Wextra -g -L../Libft -I.. $file objs_leaks/*.o -o ${file%.*} -lft -I $READLINE_DIR/include/ -L $READLINE_DIR/lib/ -lreadline ../get_next_line/get_next_line.a
	valgrind --leak-check=full ./${file%.*} > ${file%.*}.check 2>leaks_output
	diff ${file%.*}.check ${file%.*}.out
	cat leaks_output | grep -q ' 0 errors from 0 contexts' || { echo "leaks found!"; exit 1; }
done
shopt -u extglob

./integration_tests

echo FINISHED!!!!!
